// RECONSTRUCTED-V1 | NOT the lost original.  CHARGER #001 / STEP 10 — EVIDENCE PACKAGE for a LEGITIMATE proving run (C-4, Andy lock #6).
// "Produce the exact missing-input checklist for a legitimate proving run. Separate: AVAILABLE / MISSING / CONFLICTING / REQUIRES HUMAN
// DECISION. Do not fabricate substitute evidence just to get a green result."
//
// Each item says: what it is, who can supply it, the acceptance check the factory will apply, and which stage/gate code it blocks.
// tests/step10-evidence.test.mjs verifies (a) every AVAILABLE item really exists and is intact, (b) every MISSING item is really absent,
// (c) every blocker code named here is a code the factory actually emits when the input is absent. Nothing here fabricates evidence.
export const STATUS = ["AVAILABLE", "MISSING", "CONFLICTING", "REQUIRES_HUMAN_DECISION"];

export const ITEMS = [
  // ------------------------------------------------------------------ AVAILABLE
  { id: "A-01", status: "AVAILABLE", what: "Guide step 10 text (five actions) and step 2 (engine cover)", where: "recovered/src/data/admin-test-guides/charger-2016-sxt-multi-job.ts", caveat: "Recovered code. It is the canonical step text, but see CF-01…CF-08 for where other sources disagree with it." },
  { id: "A-02", status: "AVAILABLE", what: "Step 10 image prompt (spec for a text-only generated raster)", where: "recovered/doc-derived/step-10-handoff-prompt.txt", caveat: "DOCUMENTATION-DERIVED: the original prompt file is lost; this is the text a report quoted. It is a SPEC, not evidence about the car." },
  { id: "A-03", status: "AVAILABLE", what: "Old Step 10 manifest (PENDING — empty photo-route skeleton)", where: "recovered/visual-sources/2016-dodge-charger-sxt-36/step-10-intake-duct.manifest.json", caveat: "Contains no source, licence or verification; useful only for its callout list and component string." },
  { id: "A-04", status: "AVAILABLE", what: "Shot-list slot for step 10 and the recovered (empty) Charger visuals registry", where: "recovered/src/data/guide-visuals/charger-2016-sxt-multi-job.ts and recovered/src/data/guide-visuals/charger-2016-sxt-multi-job.visuals.json", caveat: "Registry holds 0 visuals; step 10 shows nothing today." },
  { id: "A-05", status: "AVAILABLE", what: "Recovered contract layer (types, resolver rules, callout rules) and vehicle registry", where: "recovered/src/types/guideVisuals.ts, recovered/src/lib/guideVisuals.ts, recovered/scripts-visuals/lib.mjs, recovered/visual-sources/applications.json", caveat: "Unmodified; hashes verified against SHA256SUMS before every harness run (C-4)." },
  { id: "A-06", status: "AVAILABLE", what: "The reconstructed factory itself (pipeline, canonical policy, independent-review path, replay verifier) and its tests", where: "src/, tests/", caveat: "RECONSTRUCTED, not the lost original. Proven on SYNTHETIC fixtures only." },

  // ------------------------------------------------------------------ MISSING (nothing to substitute; each is legitimately someone's to supply)
  { id: "M-01", status: "MISSING", what: "At least ONE real reference item for the intake system (OEM figure/text, parts-catalog entry, third-party guide, or an Andy-supplied photo), each with kind, source, sourceRef that lets a reviewer re-open it, rights, and what it establishes", suppliedBy: "Andy (or claude-research from a source Andy approves)", acceptance: "referenceProblems() clean for every item; usage is reference-only or corroborating-text (never an image input); ids unique", blocks: { stage: "2 reference evidence intake / EP sufficiency", codes: ["EP_NO_REFERENCES"] }, absentProof: "recovered manifest raw.source/sourceRef are empty; V3 spec lost" },
  { id: "M-02", status: "MISSING", what: "ESTABLISHED ledger rows (existence + location, each citing a real reference id) for every hero/target element that survives the conflict decisions: under the C-5 proposed contract: intake hose/resonator assembly, throttle-body clamp, air-cleaner-housing clamp, IAT connector, retaining grommet, throttle body, air-cleaner housing (canonical EP skeleton: charger-step10/canonical-step10.mjs canonicalEPSkeleton). The IAT connector's position appears only in the old prompt, with no evidence behind it", suppliedBy: "claude-research, from M-01", acceptance: "sufficiencyProblems() empty: every hero/target has established existence and location", blocks: { stage: "3b EP sufficiency (objective gate)", codes: ["EP_HERO_NOT_ESTABLISHED"] }, absentProof: "every ledger row in the draft EP is not-established (asserted by tests/charger-step10.test.mjs)" },
  { id: "M-03", status: "MISSING", what: "Only if a decision lets the image SHOW them: established fine-detail evidence for clamp fastener position / head type and for the connector's release-mechanism geometry", suppliedBy: "claude-research, from M-01", acceptance: "ledger rows for SAFETY_CRITICAL attributes are established with evidence, or render stays omit/occlude (LEDGER_SAFETY_SHOWN otherwise)", blocks: { stage: "3 evidence ledger", codes: ["LEDGER_SAFETY_SHOWN", "LEDGER_UNSUPPORTED_DRAWN"] }, absentProof: "no evidence exists for any of these attributes" },
  { id: "M-04", status: "MISSING", what: "The original Step 10 reference list / V3 artwork spec named by the shot list", suppliedBy: "Andy (if it exists anywhere, e.g. in the live repo or an older export)", acceptance: "file present at the path the shot list names; its references can then satisfy M-01", blocks: { stage: "2 reference evidence intake", codes: ["EP_NO_REFERENCES"] }, absentProof: "visual-sources/.../artwork/step-10-intake-duct.v3.spec.md is not in the recovered tree", file: "recovered/visual-sources/2016-dodge-charger-sxt-36/artwork/step-10-intake-duct.v3.spec.md" },
  { id: "M-05", status: "MISSING", what: "A generated candidate: candidate.png (16:10, >= 1600x1000, PNG) plus candidate.claims.json (generator system/model/provider, attestation flags, empty imageInputs, contractAck, licence terms)", suppliedBy: "an image generator run by Andy/Hermes against the LOCKED contract's prompt — never by Claude fabricating one", acceptance: "checkGeneration() ok: attestation by image-generator, no image inputs, valid PNG, 16:10, hash and prompt match", blocks: { stage: "5 generator capture / 6-8 provenance and admission", codes: ["ACTOR_UNAVAILABLE"] }, absentProof: "no charger-step10/drop/candidate.png", file: "charger-step10/drop/candidate.png" },
  { id: "M-06", status: "MISSING", what: "The generation provider's usage-rights terms for the provider/model actually used (U-15 decided in C-5: project asset subject to those rights)", suppliedBy: "Andy", acceptance: "license.terms.summary non-empty; ownershipAsserted false; assetClass/rightsBasis as canonical (GR_LICENSE_TERMS / GR_OWNERSHIP_CLAIM / GR_ASSET_CLASS otherwise)", blocks: { stage: "6 provenance checks", codes: ["GR_LICENSE_TERMS"] }, absentProof: "no generator has been run" },
  { id: "M-07", status: "MISSING", what: "INDEPENDENT final QA of the candidate by Hermes / ChatGPT / GPT-5.6 Sol, plus an optional internal claude-qa pass first", suppliedBy: "Hermes / ChatGPT / GPT-5.6 Sol (independent); claude-qa (internal)", acceptance: "submitIndependentReview accepts reviewer {actor: hermes, model matching GPT/ChatGPT, system matching Hermes/ChatGPT/OpenAI, rawResponseSha256} with no Claude-family names; verdict computed by code; an internal Claude PASS never admits", blocks: { stage: "10 QA / admission", codes: ["QR_SELF_QA_NOT_INDEPENDENT"] }, absentProof: "no candidate exists to review" },
  { id: "M-08", status: "MISSING", what: "Callout geometry (target and labelAt in image coordinates) for each final callout, and an independent overlay QA PASS_OVERLAY", suppliedBy: "overlay tool/Andy for geometry; Hermes for overlay QA", acceptance: "each callout has label/target/labelAt; overlayCheck by hermes returns PASS_OVERLAY (max 3 rounds)", blocks: { stage: "10 QA (overlay) / approval", codes: ["GATE_overlayQaPass", "GATE_calloutsVerified"] }, absentProof: "no image exists, so no coordinates can exist" },
  { id: "M-09", status: "MISSING", what: "Alt text and caption for the finished image", suppliedBy: "Andy (or drafted by Claude and approved by Andy)", acceptance: "both non-empty; caption carries 'Simplified illustration' (appended automatically if absent)", blocks: { stage: "11 final artifact / manifest", codes: ["PRESENTATION"] }, absentProof: "not written" },
  { id: "M-10", status: "MISSING", what: "Andy's final sign-off {approvedBy: andy, approvedOn: YYYY-MM-DD}", suppliedBy: "Andy", acceptance: "provenance.status becomes 'verified' (otherwise the recovered resolver refuses with 'not verified' and nothing is shown)", blocks: { stage: "11 final artifact / manifest", codes: ["not verified"] }, absentProof: "no approval exists" },
  { id: "M-11", status: "MISSING", what: "Live Crankcase main (guide registry, current Phase 1, current visuals registry) for integration", suppliedBy: "GitHub access (add_repo) — outside the proving run", acceptance: "gh api repo read returns 200", blocks: { stage: "integration (NOT part of the proving run)", codes: ["GITHUB_403"] }, absentProof: "gh api returns 403 for crankcase23/crankcase" },

  { id: "M-12", status: "MISSING", what: "Vehicle-specific verification of the eight facts the C-5 canonical contract refuses to assume (VV-01 grommet identity; VV-02 assembly composition; VV-03 air-box = air-cleaner housing; VV-04 clamp style/tightening side/head; VV-05 connector location/type/release; VV-06 guide sequence completeness; VV-07 attached breather/snorkel; VV-08 single-viewpoint adequacy)", suppliedBy: "Andy, from OEM service documentation or a physical 2016 Charger SXT 3.6L; recorded as reference evidence + ledger rows", acceptance: "each VV becomes established ledger rows citing a real reference (or the contract is amended where the evidence disagrees)", blocks: { stage: "3 evidence ledger / 4 contract lock", codes: ["EP_HERO_NOT_ESTABLISHED"] }, absentProof: "no reference evidence exists (docs/STEP10-CANONICAL-SPEC.md §VV)" },

  // ------------------------------------------------------------------ CONFLICTING (details: STEP10-CONFLICT-TABLE)
  { id: "C-01", status: "CONFLICTING", what: "What the hero part is and what it is called", conflicts: ["CF-01", "CF-03"], blocks: { stage: "1b cross-source consistency / EP elements", codes: [] } },
  { id: "C-02", status: "CONFLICTING", what: "Grommet and resonator: required by step text, banned by the prompt", conflicts: ["CF-02", "CF-03", "CF-05"], blocks: { stage: "EP elements / VC mustNotDepict", codes: [] } },
  { id: "C-03", status: "CONFLICTING", what: "Callout target list, order and wording", conflicts: ["CF-04", "CF-06"], blocks: { stage: "VC callouts", codes: [] } },
  { id: "C-04", status: "CONFLICTING", what: "Clamp and connector detail vs the actions the guide asks for", conflicts: ["CF-07", "CF-08"], blocks: { stage: "3 evidence ledger (safety-critical attributes)", codes: [] } },
  { id: "C-05", status: "CONFLICTING", what: "Production route (photo vs vector vs generated raster)", conflicts: ["CF-09"], blocks: { stage: "everything downstream of the route", codes: [] } },

  // ------------------------------------------------------------------ REQUIRES HUMAN DECISION
  { id: "D-01", status: "REQUIRES_HUMAN_DECISION", what: "Resolve CF-01…CF-09: C-5 proposes ONE resolution per row (docs/STEP10-CANONICAL-SPEC.md). Until Andy/Hermes accept it the recovered originals are unchanged and no ledger/contract is written", decider: "Andy / Hermes", blocks: { stage: "EP authoring", codes: [] } },
  { id: "D-02", status: "REQUIRES_HUMAN_DECISION", what: "Accept the C-5 proposed production route for CF-09 (text-only generated raster through the Guide Factory; photo and vector rejected)", decider: "Andy / Hermes", blocks: { stage: "everything", codes: [] } },
  { id: "D-03", status: "REQUIRES_HUMAN_DECISION", what: "Accept (or amend) the C-5 PROPOSED canonical Step 10 contract (docs/STEP10-CANONICAL-SPEC.md) as the answer to CF-01…CF-09 — in particular the three places where it overrides old visual wording because the guide text is the mechanical anchor: grommet shown (CF-02), resonator part of the hero (CF-03), clamp tightening point + connector visible (CF-07/08)", decider: "Andy / Hermes", blocks: { stage: "EP authoring", codes: [] } },
];
export const byStatus = (s) => ITEMS.filter((i) => i.status === s);
