import { Product } from "@/types/product";

// GENERATED by scripts/printify-sync.mjs — do not hand-edit, it gets
// overwritten on the next sync. Last synced: 2026-09-12T05:24:09.147Z
export const PRODUCTS: Product[] = [
  {
    id: "printify-6aa4db3db64b58138306526d",
    slug: "sump-mark-tee",
    name: "Sump Mark Tee",
    description: "Soft cotton tee with the Sump Mark on the chest. Crankcase Garage's shop logo, printed bold and built to last.",
    price: 21,
    category: "apparel",
    sizes: ["S","M","L","XL","2XL","3XL","4XL","5XL"],
    tileColor: "#1e293b",
    imageUrl: "https://images-api.printify.com/mockup/6aa4db3db64b58138306526d/22073/97933/sump-mark-tee.jpg?camera_label=front",
    printifyProductId: "6aa4db3db64b58138306526d",
  },
  ];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
